export enum TransactionStatus {
    REQUESTED            = 'REQUESTED',
    REJECTED_BY_BANK     = 'REJECTED_BY_BANK',
    APPROVED_BY_BANK     = 'APPROVED_BY_BANK',
    REJECTED_BY_EXPORTER = 'REJECTED_BY_EXPORTER',
    APPROVED_BY_EXPORTER = 'APPROVED_BY_EXPORTER'
}
